name: Build & Publish Symfony CLI Docker Image

on:
    workflow_dispatch: ~
    push:
        branches:
            - master
        paths:
            - symfony-cli/**

env:
    IMAGE_NAME: symfony-cli
    IMAGE_OWNER: ferror
    IMAGE_VERSION: latest

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            -
                name: login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Build Image
                uses: docker/build-push-action@v3
                with:
                    push: true
                    load: false
                    context: "{{defaultContext}}:symfony-cli"
                    tags: sylius-image:cache
                    platforms: linux/amd64,linux/arm64
                    cache-from: type=gha
                    cache-to: type=gha
